on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: ./target/x86_64-unknown-linux-musl/release/
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions-rs/cargo@v1
        run: |
          cargo xtask build-ebpf --release --target=x86_64-unknown-linux-gnu
          cargo build --release --target=x86_64-unknown-linux-musl

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ${{ env.BUILD_DIR }}
          files: |
            ./koops
          outPath: koops-x86_64-linux.tar.gz

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.BUILD_DIR }}
          asset_name: koops-x86_64-linux.tar.gz
          asset_content_type: application/gzip
